const CardData = [
  {
    id: Math.random(),
    image: "images/pizza.jpg",
    title: " pizza",
    price: "7$",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "pizza",
  },
  {
    id: Math.random(),
    image: "images/burger.jpg",
    title: " Burger",
    price: "6$",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "burger",
  },
  {
    id: Math.random(),
    image: "images/pasta.jpg",
    price: "5$",
    title: "pasta white ",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "pasta",
  },
  {
    id: Math.random(),
    image: "images/drink2.jpg",
    price: "3$",
    title: "limon",
    descraption: "It is very good drink",
    btn: "Buy Now",
    catagory: "drink",
  },
  {
    id: Math.random(),
    image: "images/drink1.jpg",
    price: "4$",
    title: "Drink",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "drink",
  },
  {
    id: Math.random(),
    image: "images/pizza2.jpg",
    title: "pizza",
    price: "6$",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "pizza",
  },
  {
    id: Math.random(),
    image: "images/pasta2.jpg",
    title: "pasta",
    price: "6$",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "pasta",
  },
  {
    id: Math.random(),
    image: "images/drink.jpg",
    price: "5$",
    title: "cofaa",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "drink",
  },
  {
    id: Math.random(),
    image: "images/burger2.jpg",
    price: "3$",
    title: "burger",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "burger",
  },
  {
    id: Math.random(),
    image: "images/sweet.jpg",
    price: "4$",
    title: "sweet",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "sweet",
  },
  {
    id: Math.random(),
    image: "images/pizza.jpg",
    title: "pizza",
    price: "8$",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "pizza",
  },
  // {
  //   id: Math.random(),
  //   image: "images/burger.jpg",
  //   title: "Smach Burger",
  //   price: "6$",
  //   descraption: "It is very good test and healthy for us",
  //   btn: "Buy Now",
  // },
  // {
  //   id: Math.random(),
  //   image: "images/pizza2.jpg",
  //   price: "5$",
  //   title: "pizza checken",
  //   descraption: "It is very good test and healthy for us",
  //   btn: "Buy Now",
  // },
  // {
  //   id: Math.random(),
  //   image: "images/rice.jpg",
  //   price: "3$",
  //   title: "pizza checken",
  //   descraption: "It is very good test and healthy for us",
  //   btn: "Buy Now",
  // },
  {
    id: Math.random(),
    image: "images/sweet2.jpg",
    price: "4$",
    title: "sweet",
    descraption: "It is very good test and healthy for us",
    btn: "Buy Now",
    catagory: "sweet",
  },
];

export default CardData;
